# This is a basic workflow to help you get started with Actions

name: Reporting

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      database:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testDb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: install modules
        run: |
          yarn install

      - name: db migration
        run: yarn dbup

      - name: setup report directory
        run: |
          git fetch --prune
          git branch reports origin/reports
          git worktree add reports

      - name: Coverage
        timeout-minutes: 3
        run: |
          mv .env.test .env
          yarn test:coverage

      - name: TypeDoc
        run: yarn doc

      - name: Static analysis
        run: yarn plato

      - name: git setting
        run: |
          git config --local user.email "tokutomi@degino.com"
          git config --local user.name "Tommy109"

      - name: git commit & push
        run: |
          cd reports
          git add .
          git commit -m 'Reports auto update'
          git push origin reports
